development:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: 1234
      encoding: utf8

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: root
      password: foradian

production:
      host: localhost
      adapter: mysql
      database: fedena_production
      port: 3306
      username: root
      password: 1234
      encoding: utf8
cucumber:
  <<: *test
